baseURL = '/'
languageCode = 'cs-cz'
title = 'čn'
theme = 'ananke'
canonifyURLs = true
DefaultContentLanguage = 'cs'
SectionPagesMenu = 'main'
Paginate = 12
summaryLength = 20
[taxonomies]
  tag = 'tags'
  category = 'categories'
  quality = 'qualities'
[params]
  favicon = 'favicon.ico'
  MainSections = ['posts','recepty', 'výlety']
  body_classes = 'avenir bg-near-white'
