baseURL = '/'
languageCode = 'cs-cz'
title = 'červený notes'
theme = 'ananke'
canonifyURLs = true
DefaultContentLanguage = 'cs'
SectionPagesMenu = 'main'
Paginate = 12
summaryLength = 20
[params]
  favicon = 'favicon.ico'
  MainSections = ['posts','recepty', 'výlety']
  body_classes = 'avenir bg-near-white'
